/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import classesControle.ControleImovel;
import classesControle.ControleVenda;
import classesEntidade.Comprador;
import classesEntidade.Contrato_Aluguel;
import classesEntidade.Contrato_Venda;
import classesEntidade.Corretor;
import classesEntidade.Proprietario;
import classesEntidade.Imovel;
import classesEntidade.Locatario;
import classesEntidade.Situacao_Contrato;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author welerson
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TesteTela
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        btLoginCorretor = new javax.swing.JButton();
        btLoginAdm = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bem vindo ao Sistema Imobiliário");

        btLoginCorretor.setText("Sou Corretor");
        btLoginCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginCorretorActionPerformed(evt);
            }
        });

        btLoginAdm.setText("Sou Administrador");
        btLoginAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginAdmActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btLoginCorretor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(btLoginAdm)
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLoginCorretor)
                    .addComponent(btLoginAdm))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginCorretorActionPerformed
        // Redirecionar para a tela de Login Corretor
    }//GEN-LAST:event_btLoginCorretorActionPerformed

    private void btLoginAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginAdmActionPerformed
        //Redirecionar Tela Login Adm
    }//GEN-LAST:event_btLoginAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        Imovel im = new Imovel();
        im = im.getImovelById(2);
        Contrato_Aluguel c_v = new Contrato_Aluguel();
        /*        
        Locatario l = new Locatario();
        l.setCpf("0514826328");
        l.setEmail("ed@gmail.com");
        l.setNomeCompleto("Carlos Alberto");
       
        l.cadastrarLocatario(l);
        l = l.buscarLocatario("0514826328");
        
        
        Corretor cor = new Corretor();
        cor = cor.buscarCorretor("98399457504");
        
        c_v.setLocatario(l);
        c_v.setCorretor(cor);
        c_v.setDataFechamento("22/03/2019");
        c_v.setDescricaoAluguel("Descricao teste!!");
        c_v.setImovel(im);
        c_v.setSituacao_contrato(Situacao_Contrato.EM_ABERTO);
        c_v.setValorAluguel(500);
        c_v.setDataFim("10/04/2019");
        
        c_v.abrirContrato(); 
        */
               
        for(Contrato_Aluguel ca: c_v.getContratosVigentes()){
            System.out.println("Descricao: "+ca.getDescricaoAluguel());
            System.out.println("Dada Fim: "+ca.getDataFim());
        }
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
 //               new TelaPrincipal().setVisible(true); DESCOMENTAR PARA EXECUTAR A TELA
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLoginAdm;
    private javax.swing.JButton btLoginCorretor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
